name: Python Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask  # Install Flask module
        #pip install pytest  # Install pytest
        

    - name: Deploy application
      run: |
       nohup python a.py > /dev/null 2>&1 &

